-- Drop if exists (idempotent for H2 in tests)
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name              VARCHAR(120)      NOT NULL,
                       email             VARCHAR(160),
                       phone_number      VARCHAR(40)       NOT NULL,
                       address           VARCHAR(255)      NOT NULL,
                       created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_email ON users(email);
