create table if not exists accounts (
                                        id bigint generated by default as identity primary key,
                                        user_id bigint not null,
                                        account_type varchar(40) not null,
    currency varchar(10) not null,
    balance decimal(19,2) not null default 0,
    constraint fk_accounts_user
    foreign key (user_id) references users(id)
    );
